#include <stdio.h>


#include "token_printer.h"
#include "tokenizer.h"


static void printTokenType(TokenType type) {
    #define GENERATE_CASE(case_, string) case case_: printf(string); break;


    switch (type) {
        GENERATE_CASE(TOKEN_PRINT, "TOKEN_PRINT")
        GENERATE_CASE(TOKEN_PRINTLN, "TOKEN_PRINTLN")
        GENERATE_CASE(TOKEN_VAR, "TOKEN_VAR")
        GENERATE_CASE(TOKEN_IF, "TOKEN_IF")
        GENERATE_CASE(TOKEN_ELSE_IF, "TOKEN_ELSE_IF")
        GENERATE_CASE(TOKEN_ELSE, "TOKEN_ELSE")
        GENERATE_CASE(TOKEN_FOR, "TOKEN_FOR")
        GENERATE_CASE(TOKEN_BREAK, "TOKEN_BREAK")
        GENERATE_CASE(TOKEN_CONTINUE, "TOKEN_CONTINUE")
        GENERATE_CASE(TOKEN_FUNC, "TOKEN_FUNC")
        GENERATE_CASE(TOKEN_RETURN, "TOKEN_RETURN")
        GENERATE_CASE(TOKEN_STRUCT, "TOKEN_STRUCT")
        GENERATE_CASE(TOKEN_INIT, "TOKEN_INIT")
        GENERATE_CASE(TOKEN_THIS, "TOKEN_THIS")
        GENERATE_CASE(TOKEN_EXTENDS, "TOKEN_EXTENDS")
        GENERATE_CASE(TOKEN_SUPER, "TOKEN_SUPER")
        GENERATE_CASE(TOKEN_AND, "TOKEN_AND")
        GENERATE_CASE(TOKEN_OR, "TOKEN_OR")
        GENERATE_CASE(TOKEN_TRUE, "TOKEN_TRUE")
        GENERATE_CASE(TOKEN_FALSE, "TOKEN_FALSE")
        GENERATE_CASE(TOKEN_NIL, "TOKEN_NIL")
        GENERATE_CASE(TOKEN_STRING, "TOKEN_STRING")
        GENERATE_CASE(TOKEN_NUMBER, "TOKEN_NUMBER")
        GENERATE_CASE(TOKEN_IDENTIFIER, "TOKEN_IDENTIFIER")
        GENERATE_CASE(TOKEN_EOF, "TOKEN_EOF")
        GENERATE_CASE(TOKEN_ERROR, "TOKEN_ERROR")
        GENERATE_CASE(TOKEN_PLUS, "TOKEN_PLUS")
        GENERATE_CASE(TOKEN_PLUS_EQUAL, "TOKEN_PLUS_EQUAL")
        GENERATE_CASE(TOKEN_MINUS, "TOKEN_MINUS")
        GENERATE_CASE(TOKEN_MINUS_EQUAL, "TOKEN_MINUS_EQUAL")
        GENERATE_CASE(TOKEN_STAR, "TOKEN_STAR")
        GENERATE_CASE(TOKEN_STAR_STAR, "TOKEN_STAR_STAR")
        GENERATE_CASE(TOKEN_STAR_EQUAL, "TOKEN_STAR_EQUAL")
        GENERATE_CASE(TOKEN_STAR_STAR_EQUAL, "TOKEN_STAR_STAR_EQUAL")
        GENERATE_CASE(TOKEN_SLASH, "TOKEN_SLASH")
        GENERATE_CASE(TOKEN_SLASH_EQUAL, "TOKEN_SLASH_EQUAL")
        GENERATE_CASE(TOKEN_PERCENT, "TOKEN_PERCENT")
        GENERATE_CASE(TOKEN_PERCENT_EQUAL, "TOKEN_PERCENT_EQUAL")
        GENERATE_CASE(TOKEN_EQUAL, "TOKEN_EQUAL")
        GENERATE_CASE(TOKEN_EQUAL_EQUAL, "TOKEN_EQUAL_EQUAL")
        GENERATE_CASE(TOKEN_BANG, "TOKEN_BANG")
        GENERATE_CASE(TOKEN_BANG_EQUAL, "TOKEN_BANG_EQUAL")
        GENERATE_CASE(TOKEN_LESSER, "TOKEN_LESSER")
        GENERATE_CASE(TOKEN_LESSER_EQUAL, "TOKEN_LESSER_EQUAL")
        GENERATE_CASE(TOKEN_GREATER, "TOKEN_GREATER")
        GENERATE_CASE(TOKEN_GREATER_EQUAL, "TOKEN_GREATER_EQUAL")
        GENERATE_CASE(TOKEN_SEMICOLON, "TOKEN_SEMICOLON")
        GENERATE_CASE(TOKEN_COLON, "TOKEN_COLON")
        GENERATE_CASE(TOKEN_COMMA, "TOKEN_COMMA")
        GENERATE_CASE(TOKEN_LEFT_PAREN, "TOKEN_LEFT_PAREN")
        GENERATE_CASE(TOKEN_RIGHT_PAREN, "TOKEN_RIGHT_PAREN")
        GENERATE_CASE(TOKEN_LEFT_BRACE, "TOKEN_LEFT_BRACE")
        GENERATE_CASE(TOKEN_RIGHT_BRACE, "TOKEN_RIGHT_BRACE")
        GENERATE_CASE(TOKEN_DOT, "TOKEN_DOT")
        GENERATE_CASE(TOKEN_QUESTION, "TOKEN_QUESTION")
        GENERATE_CASE(TOKEN_NEWLINE, "TOKEN_NEWLINE")
    }

    #undef GENERATE_CASE
}

void printTokens(const Tokens *tokens) {
    printf("\ncount : %llu\n\n", tokens->count);

    for (int i = 0; i < tokens->count; i++) {
        const Token *token = &tokens->tokens[i];

        printf("[");
        printTokenType(tokens->tokens[i].type);
        printf(", '%.*s', %d, %d]\n", token->length, token->start, token->length, token->line);
    }
}
